/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Korisnik
 */
public class FrmMainKorisnik extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainKorisnik
     */
    public FrmMainKorisnik() {
        initComponents();
        setTitle("Početna");
        //setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurrentUser = new javax.swing.JLabel();
        btnKraj = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuPrijava = new javax.swing.JMenu();
        jmiPrijavaZaKurs = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCurrentUser.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        lblCurrentUser.setText("jLabel1");
        lblCurrentUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnKraj.setBackground(new java.awt.Color(255, 51, 51));
        btnKraj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKraj.setForeground(new java.awt.Color(255, 255, 255));
        btnKraj.setText("Kraj rada");

        menuPrijava.setText("Prijava");

        jmiPrijavaZaKurs.setText("Prijava na kurs");
        menuPrijava.add(jmiPrijavaZaKurs);

        jMenuBar1.add(menuPrijava);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 282, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 227, Short.MAX_VALUE)
                .addComponent(btnKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKraj;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jmiPrijavaZaKurs;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JMenu menuPrijava;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblCurrentUser() {
        return lblCurrentUser;
    }

    public void setLblCurrentUser(JLabel lblCurrentUser) {
        this.lblCurrentUser = lblCurrentUser;
    }

    public void addKrajBtnActionListener(ActionListener actionListener) {
        btnKraj.addActionListener(actionListener);
    }

    public void addPrijavaActionListener(ActionListener actionListener) {
        jmiPrijavaZaKurs.addActionListener(actionListener);
    }


}
