/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.form;

import java.awt.event.ActionListener;
import javax.swing.JFrame;
import javax.swing.JLabel;

/**
 *
 * @author Korisnik
 */
public class FrmMainAdmin extends javax.swing.JFrame {

    /**
     * Creates new form FrmMainAdmin
     */
    public FrmMainAdmin() {
        initComponents();
        setTitle("Početna strana");
        //setLocationRelativeTo(null);
        setExtendedState(JFrame.MAXIMIZED_BOTH);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCurrentUser = new javax.swing.JLabel();
        btnKraj = new javax.swing.JButton();
        menuBar = new javax.swing.JMenuBar();
        menuKurs = new javax.swing.JMenu();
        jmiKreirajKurs = new javax.swing.JMenuItem();
        jmiPretraziKurs = new javax.swing.JMenuItem();
        menuGrupa = new javax.swing.JMenu();
        jmiKreirajGrupu = new javax.swing.JMenuItem();
        jmiPretraziGrupu = new javax.swing.JMenuItem();
        jmiRasporedi = new javax.swing.JMenuItem();
        menuOpis = new javax.swing.JMenu();
        jmiSoftver = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCurrentUser.setFont(new java.awt.Font("Lucida Calligraphy", 0, 24)); // NOI18N
        lblCurrentUser.setText("jLabel1");
        lblCurrentUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        btnKraj.setBackground(new java.awt.Color(255, 51, 51));
        btnKraj.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKraj.setForeground(new java.awt.Color(255, 255, 255));
        btnKraj.setText("Kraj rada");

        menuKurs.setText("Kurs");

        jmiKreirajKurs.setText("Kreiraj kurs");
        menuKurs.add(jmiKreirajKurs);

        jmiPretraziKurs.setText("Pretraži kurs");
        menuKurs.add(jmiPretraziKurs);

        menuBar.add(menuKurs);

        menuGrupa.setText("Grupa");

        jmiKreirajGrupu.setText("Kreiraj grupu");
        menuGrupa.add(jmiKreirajGrupu);

        jmiPretraziGrupu.setText("Pretraži grupu");
        menuGrupa.add(jmiPretraziGrupu);

        jmiRasporedi.setText("Rasporedi polaznike u grupu");
        menuGrupa.add(jmiRasporedi);

        menuBar.add(menuGrupa);

        menuOpis.setText("Opis");

        jmiSoftver.setText("O softveru");
        menuOpis.add(jmiSoftver);

        menuBar.add(menuOpis);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 303, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblCurrentUser, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 235, Short.MAX_VALUE)
                .addComponent(btnKraj, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnKraj;
    private javax.swing.JMenuItem jmiKreirajGrupu;
    private javax.swing.JMenuItem jmiKreirajKurs;
    private javax.swing.JMenuItem jmiPretraziGrupu;
    private javax.swing.JMenuItem jmiPretraziKurs;
    private javax.swing.JMenuItem jmiRasporedi;
    private javax.swing.JMenuItem jmiSoftver;
    private javax.swing.JLabel lblCurrentUser;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuGrupa;
    private javax.swing.JMenu menuKurs;
    private javax.swing.JMenu menuOpis;
    // End of variables declaration//GEN-END:variables

    public JLabel getLblCurrentUser() {
        return lblCurrentUser;
    }

    public void setLblCurrentUser(JLabel lblCurrentUser) {
        this.lblCurrentUser = lblCurrentUser;
    }

    public void addKrajBtnActionListener(ActionListener actionListener) {
        btnKraj.addActionListener(actionListener);
    }

    public void jmiSoftverAddActionListener(ActionListener actionListener) {
        jmiSoftver.addActionListener(actionListener);
    }

    public void jmiKreirajKursAddActionListener(ActionListener actionListener) {
        jmiKreirajKurs.addActionListener(actionListener);
    }

    public void jmiPretraziKursAddActionListener(ActionListener actionListener) {
        jmiPretraziKurs.addActionListener(actionListener);
    }

    public void jmiKreirajGrupuAddActionListener(ActionListener actionListener) {
        jmiKreirajGrupu.addActionListener(actionListener);
    }

    public void jmiPretraziGrupuAddActionListener(ActionListener actionListener) {
        jmiPretraziGrupu.addActionListener(actionListener);
    }

    public void jmiRasporediAddActionListener(ActionListener actionListener) {
        jmiRasporedi.addActionListener(actionListener);
    }


}
