/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view.form;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JTable;
import javax.swing.JTextField;

/**
 *
 * @author Korisnik
 */
public class FrmPretragaGrupa extends javax.swing.JDialog {

    /**
     * Creates new form FrmPretragaGrupe
     */
    public FrmPretragaGrupa(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaGrupa = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtNazivGrupe = new javax.swing.JTextField();
        btnFiltriraj = new javax.swing.JButton();
        btnDetalji = new javax.swing.JButton();
        btnPrikaziGrupe = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnKreirajIzvestaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tabelaGrupa.setBackground(new java.awt.Color(204, 255, 204));
        tabelaGrupa.setForeground(new java.awt.Color(0, 0, 0));
        tabelaGrupa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabelaGrupa);

        jLabel2.setText("Naziv grupe:");

        txtNazivGrupe.setBackground(new java.awt.Color(204, 255, 204));
        txtNazivGrupe.setForeground(new java.awt.Color(0, 0, 0));

        btnFiltriraj.setBackground(new java.awt.Color(0, 102, 0));
        btnFiltriraj.setForeground(new java.awt.Color(255, 255, 255));
        btnFiltriraj.setText("Filtriraj");

        btnDetalji.setBackground(new java.awt.Color(0, 102, 0));
        btnDetalji.setForeground(new java.awt.Color(255, 255, 255));
        btnDetalji.setText("Detalji");

        btnPrikaziGrupe.setBackground(new java.awt.Color(0, 102, 0));
        btnPrikaziGrupe.setForeground(new java.awt.Color(255, 255, 255));
        btnPrikaziGrupe.setText("Prikaži sve grupe");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setText("Pretraga grupa");

        btnKreirajIzvestaj.setBackground(new java.awt.Color(0, 102, 0));
        btnKreirajIzvestaj.setForeground(new java.awt.Color(255, 255, 255));
        btnKreirajIzvestaj.setText("Kreiraj izveštaj");
        btnKreirajIzvestaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKreirajIzvestajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNazivGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnFiltriraj, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(37, 37, 37)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnPrikaziGrupe)
                                    .addGap(18, 18, 18)
                                    .addComponent(btnKreirajIzvestaj)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnDetalji))
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 557, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNazivGrupe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnFiltriraj))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDetalji)
                    .addComponent(btnPrikaziGrupe)
                    .addComponent(btnKreirajIzvestaj))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKreirajIzvestajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKreirajIzvestajActionPerformed

    }//GEN-LAST:event_btnKreirajIzvestajActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDetalji;
    private javax.swing.JButton btnFiltriraj;
    private javax.swing.JButton btnKreirajIzvestaj;
    private javax.swing.JButton btnPrikaziGrupe;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabelaGrupa;
    private javax.swing.JTextField txtNazivGrupe;
    // End of variables declaration//GEN-END:variables

    public void getBtnDetaljiAddActionListener(ActionListener actionListener) {
        btnDetalji.addActionListener(actionListener);
    }

    public void getBtnFiltrirajAddActionListener(ActionListener actionListener) {
        btnFiltriraj.addActionListener(actionListener);
    }

    public void getBtnPrikaziSveAddActionListener(ActionListener actionListener) {
        btnPrikaziGrupe.addActionListener(actionListener);
    }
    
    public void getBtnKreirajIzvestajAddActionListener(ActionListener actionListener) {
        btnKreirajIzvestaj.addActionListener(actionListener);
    }

    public JButton getBtnDetalji() {
        return btnDetalji;
    }

    public JButton getBtnFiltriraj() {
        return btnFiltriraj;
    }

    public JButton getBtnPrikaziGrupe() {
        return btnPrikaziGrupe;
    }

    public JTable getTabelaGrupa() {
        return tabelaGrupa;
    }

    public JTextField getTxtNazivGrupe() {
        return txtNazivGrupe;
    }


}
